// Central content + config source. Keeping copy here makes the
// storytelling easy to tune without touching component logic.

import { desktopAsset, mobileAsset, reelAsset, workAsset } from '../config/assets';
import { HERO_FRAMES } from '../data/heroManifest';
import { FEATURED_REEL } from '../data/videoPortfolio';

export const BRAND = {
  name: 'wenilo',
  promise: 'Get More Customers',
  email: 'hello@wenilo.com',
  socials: [
    { label: 'LinkedIn', href: 'https://www.linkedin.com' },
    { label: 'Instagram', href: 'https://www.instagram.com' },
    { label: 'Email', href: 'mailto:hello@wenilo.com' },
  ],
};

export const NAV_LINKS = [
  { label: '3D Websites', to: '/#3d-websites', section: '3d-websites' },
  { label: 'AI Voice Agents', to: '/voice-agents', section: 'voice-agents' },
  { label: 'AI Video Production', to: '/ai-video-production', section: 'ai-video' },
  { label: 'Contact', to: '/#contact', section: 'contact' },
];

export const CTA = {
  primary: 'Schedule a Call',
  secondary: 'View Our Work',
};

// Single wenilo booking event — every CTA opens THIS same Calendly form
// (via the global popup, see contexts/CalendlyContext). Change it in one place.
export const CALENDLY_URL = 'https://calendly.com/vaibhavchougule2512/30min';

// Scroll-driven hero image sequence (Apple-style). Frames are served as
// pre-optimised WebP from Cloudflare R2 (assets.wenilo.com).
//
// Frame filenames are pinned in src/data/heroManifest.js (1-based order),
// generated by `node scripts/build-hero-manifest.mjs`. getUrl indexes it.
//
// Device split: desktop/tablet play the landscape set; phones play a
// dedicated portrait (9:16) set. Same filenames, different R2 folder
// (desktop-assets/ vs mobile-assets/). HeroSequence picks one at load via
// matchMedia, so a phone only ever downloads the portrait frames.
export const HERO_SEQUENCE = {
  count: HERO_FRAMES.desktop.length,
  desktop: {
    getUrl: (i) => desktopAsset(HERO_FRAMES.desktop[i - 1]),
  },
  mobile: {
    getUrl: (i) => mobileAsset(HERO_FRAMES.mobile[i - 1]),
  },
};

// Shared id used by GSAP Flip to morph the home circle into the
// Voice Agents hero object across the route change.
export const VOICE_FLIP_ID = 'voice-sphere';

// Responsive media sources for the ServiceShowcase cards. Desktop/tablet
// use the landscape asset; mobile uses a dedicated portrait (9:16) cut.
// ResponsiveVideo resolves exactly one per device (no double download)
// and degrades to an elegant placeholder until these files exist. Served
// from Cloudflare R2 under website/{desktop,mobile}-assets/; upload keeping
// these filenames to go live — paths are already wired, no code change needed.
export const MEDIA = {
  website: {
    desktop: desktopAsset('website.mp4'),
    mobile: mobileAsset('website.mp4'),
  },
  // Phase 1: the card plays a real reel instead of the placeholder. The file
  // lives OUTSIDE the website/ prefix, under ai-video-production/ — hence
  // reelAsset() rather than desktopAsset(). Both cuts point at the DESKTOP
  // file on purpose: it is the asset supplied for this test and, at ~23MB,
  // less than half the weight of the 1080-wide mobile cut (~55MB), which is
  // far too heavy for a teaser card on a phone.
  videoProduction: {
    desktop: reelAsset('desktop', '01/0404%20(1).mp4'),
    mobile: reelAsset('desktop', '01/0404%20(1).mp4'),
  },
  // Optional fullscreen hero-video variant (see components/hero/HeroMedia).
  hero: {
    desktop: desktopAsset('hero.mp4'),
    mobile: mobileAsset('hero.mp4'),
    posterDesktop: desktopAsset('hero.webp'),
    posterMobile: mobileAsset('hero.webp'),
  },
};

// The wedding-invitation collection that drives the /ai-video-production
// showcase. Read straight off FEATURED_REEL so the Work grid shares ONE asset
// configuration with that page — these R2 paths are never copied.
const WEDDING_REELS = FEATURED_REEL.find((p) => p.variant === 'reels')?.reels ?? [];

// The masonry grid. `span` drives the aspect ratio and therefore the rhythm.
//
// Two entries carry `reel` + `to`: WorkCard plays that reel through the SAME
// ReelVideo player the AI Video Production page uses and turns the whole card
// into a router Link. Entries without those keys keep the studio placeholder
// and are untouched. Grid order is DOM order; CSS columns fill top-to-bottom,
// so w1 and w5 are the first and third cards a visitor sees on a 3-up layout.
export const WORK_ITEMS = [
  {
    id: 'w1',
    title: 'AI Video Production',
    tag: 'AI Product Ad',
    span: 'tall',
    // Product-ad reel from the ai-video-production/desktop tree.
    // No separate mobile cut exists; both point at the same desktop source.
    reel: {
      desktopVideo: reelAsset('desktop', 'product-add-3/hf_20260730_042703_b9cf9e99-aa69-43d1-98b6-783a680f285f.mp4'),
      mobileVideo:  reelAsset('desktop', 'product-add-3/hf_20260730_042703_b9cf9e99-aa69-43d1-98b6-783a680f285f.mp4'),
    },
    to: '/ai-video-production',
  },
  { id: 'w2', title: 'Nova Voice', tag: 'AI Voice Agent', span: 'wide' },
  { id: 'w3', title: 'Atlas Studio', tag: 'AI Video', span: 'normal' },
  { id: 'w4', title: 'Vanta Labs', tag: '3D Website', span: 'normal' },
  {
    id: 'w5',
    title: 'AI Video Production',
    tag: 'Wedding Invitation',
    span: 'tall',
    reel: WEDDING_REELS[1],
    to: '/ai-video-production',
  },
  { id: 'w6', title: 'Orbit Health', tag: 'AI Voice Agent', span: 'wide' },
];

export const PROCESS_STEPS = [
  { n: '01', title: 'Discover', copy: 'We map the fastest path from stranger to customer.' },
  { n: '02', title: 'Design', copy: 'Cinematic direction, engineered to convert.' },
  { n: '03', title: 'Build', copy: 'Award-winning craft. 60fps. Zero compromise.' },
  { n: '04', title: 'Launch', copy: 'We ship, measure and refine in the real world.' },
  { n: '05', title: 'Get More Customers', copy: 'The only metric that matters. Growth.' },
];
