// Central content + config source. Keeping copy here makes the
// storytelling easy to tune without touching component logic.

import { cdnImg, cdnVid, cdnImgId } from '../config/cloudinary';
import { HERO_FRAMES } from '../data/heroManifest';

export const BRAND = {
  name: 'MotionOfAI',
  promise: 'Get More Customers',
  email: 'hello@motionofai.com',
  socials: [
    { label: 'LinkedIn', href: 'https://www.linkedin.com' },
    { label: 'Instagram', href: 'https://www.instagram.com' },
    { label: 'Email', href: 'mailto:hello@motionofai.com' },
  ],
};

export const NAV_LINKS = [
  { label: '3D Websites', to: '/#3d-websites', section: '3d-websites' },
  { label: 'AI Voice Agents', to: '/voice-agents', section: 'voice-agents' },
  { label: 'AI Video Production', to: '/ai-video-production', section: 'ai-video' },
  { label: 'Contact', to: '/#contact', section: 'contact' },
];

export const CTA = {
  primary: 'Schedule a Call',
  secondary: 'View Our Work',
};

// Single MotionOfAI booking event — every CTA opens THIS same Calendly form
// (via the global popup, see contexts/CalendlyContext). Change it in one place.
export const CALENDLY_URL = 'https://calendly.com/vaibhavchougule2512/30min';

// Scroll-driven hero image sequence (Apple-style). Frames are served from
// Cloudinary with f_auto,q_auto, so each browser gets the best format
// (AVIF/WebP/JPG) and compression from a single upload — no per-frame JPG
// fallback needed.
//
// Cloudinary stored each frame with a random unique suffix
// (ezgif-frame-001_irwj3o), so there is NO URL formula — the exact
// public_ids are pinned in src/data/heroManifest.js (1-based order),
// generated by `node scripts/build-hero-manifest.mjs`. getUrl indexes it.
//
// Device split: desktop/tablet play the landscape set; phones play a
// dedicated portrait (9:16) set. HeroSequence picks one at load via
// matchMedia, so a phone only ever downloads the portrait frames.
export const HERO_SEQUENCE = {
  count: HERO_FRAMES.desktop.length,
  desktop: {
    getUrl: (i) => cdnImgId(HERO_FRAMES.desktop[i - 1]),
  },
  mobile: {
    getUrl: (i) => cdnImgId(HERO_FRAMES.mobile[i - 1]),
  },
};

// Shared id used by GSAP Flip to morph the home circle into the
// Voice Agents hero object across the route change.
export const VOICE_FLIP_ID = 'voice-sphere';

// Responsive media sources for the ServiceShowcase cards. Desktop/tablet
// use the landscape asset; mobile uses a dedicated portrait (9:16) cut.
// ResponsiveVideo resolves exactly one per device (no double download)
// and degrades to an elegant placeholder until these files exist. Served
// from Cloudinary under the MotionOfAI/ root; upload keeping these names +
// folders to go live — paths are already wired, no code change needed.
export const MEDIA = {
  website: {
    desktop: cdnVid('Portfolio/desktop/website.mp4'),
    mobile: cdnVid('Portfolio/mobile/website.mp4'),
  },
  videoProduction: {
    desktop: cdnVid('AIVideoProduction/desktop/video-production.mp4'),
    mobile: cdnVid('AIVideoProduction/mobile/video-production.mp4'),
  },
  // Optional fullscreen hero-video variant (see components/hero/HeroMedia).
  hero: {
    desktop: cdnVid('Hero/Desktop/hero.mp4'),
    mobile: cdnVid('Hero/Mobile/hero.mp4'),
    posterDesktop: cdnImg('Hero/Desktop/hero.webp'),
    posterMobile: cdnImg('Hero/Mobile/hero.webp'),
  },
};

export const WORK_ITEMS = [
  { id: 'w1', title: 'Helios Commerce', tag: '3D Website', span: 'tall' },
  { id: 'w2', title: 'Nova Voice', tag: 'AI Voice Agent', span: 'wide' },
  { id: 'w3', title: 'Atlas Studio', tag: 'AI Video', span: 'normal' },
  { id: 'w4', title: 'Vanta Labs', tag: '3D Website', span: 'normal' },
  { id: 'w5', title: 'Lumen Retail', tag: 'AI Video', span: 'tall' },
  { id: 'w6', title: 'Orbit Health', tag: 'AI Voice Agent', span: 'wide' },
];

export const PROCESS_STEPS = [
  { n: '01', title: 'Discover', copy: 'We map the fastest path from stranger to customer.' },
  { n: '02', title: 'Design', copy: 'Cinematic direction, engineered to convert.' },
  { n: '03', title: 'Build', copy: 'Award-winning craft. 60fps. Zero compromise.' },
  { n: '04', title: 'Launch', copy: 'We ship, measure and refine in the real world.' },
  { n: '05', title: 'Get More Customers', copy: 'The only metric that matters. Growth.' },
];
